[package]
name = "map"
version = "0.1.0"
authors = []
edition = "2021"

[[bin]]
name = "map"
path = "./src/rust/main.rs"

[dependencies]
iced = { version = "0.9.0", features = ["canvas"] }
iced_web = "0.4.0"
serde = "1.0"
serde_json = "1.0"
